In [1]:
input = [1749,1897,881,1736,1161,1720,1676,305,264,1904,1880,1173,483,1978,1428,1635,1386,1858,1602,1916,1906,1212,1730,1777,1698,1845,1812,1922,
1729,
1803,
1761,
1901,
1748,
1188,
1964,
1935,
1919,
1810,
1567,
1849,
1417,
1452,
54,
1722,
1784,
1261,
1744,
1594,
1526,
1771,
1762,
1894,
1717,
1716,
51,
1955,
1143,
1741,
1999,
1775,
1944,
1983,
1962,
1198,
1553,
1835,
1867,
1662,
1461,
1811,
1764,
1726,
1927,
1179,
1468,
1948,
1813,
1213,
1905,
1371,
1751,
1215,
1392,
1798,
1823,
1815,
1923,
1942,
1987,
1887,
1838,
1395,
2007,
1479,
1752,
1945,
1621,
1538,
1937,
565,
1969,
1493,
1291,
1438,
1578,
1770,
2005,
1703,
1712,
1943,
2003,
1499,
1903,
1760,
1950,
1990,
1185,
1809,
1337,
1358,
1743,
1707,
1671,
1788,
1785,
1972,
1863,
1690,
1512,
1963,
1825,
1460,
1828,
1902,
1874,
1755,
1951,
1830,
1767,
1787,
1373,
1709,
1514,
1807,
1791,
1724,
1859,
1590,
1976,
1572,
1947,
1913,
1995,
1728,
1624,
1731,
1706,
1782,
1994,
1851,
1843,
1773,
1982,
1685,
2001,
1346,
1200,
1746,
1520,
972,
1834,
1909,
2008,
1733,
1960,
1280,
1879,
1203,
1979,
1133,
1647,
1282,
1684,
860,
1444,
1780,
1989,
1795,
1819,
1797,
1842,
1796,
1457,
1839,
1853,
1711,
1883,
1146,
1734,
1389]
input

[1749,
 1897,
 881,
 1736,
 1161,
 1720,
 1676,
 305,
 264,
 1904,
 1880,
 1173,
 483,
 1978,
 1428,
 1635,
 1386,
 1858,
 1602,
 1916,
 1906,
 1212,
 1730,
 1777,
 1698,
 1845,
 1812,
 1922,
 1729,
 1803,
 1761,
 1901,
 1748,
 1188,
 1964,
 1935,
 1919,
 1810,
 1567,
 1849,
 1417,
 1452,
 54,
 1722,
 1784,
 1261,
 1744,
 1594,
 1526,
 1771,
 1762,
 1894,
 1717,
 1716,
 51,
 1955,
 1143,
 1741,
 1999,
 1775,
 1944,
 1983,
 1962,
 1198,
 1553,
 1835,
 1867,
 1662,
 1461,
 1811,
 1764,
 1726,
 1927,
 1179,
 1468,
 1948,
 1813,
 1213,
 1905,
 1371,
 1751,
 1215,
 1392,
 1798,
 1823,
 1815,
 1923,
 1942,
 1987,
 1887,
 1838,
 1395,
 2007,
 1479,
 1752,
 1945,
 1621,
 1538,
 1937,
 565,
 1969,
 1493,
 1291,
 1438,
 1578,
 1770,
 2005,
 1703,
 1712,
 1943,
 2003,
 1499,
 1903,
 1760,
 1950,
 1990,
 1185,
 1809,
 1337,
 1358,
 1743,
 1707,
 1671,
 1788,
 1785,
 1972,
 1863,
 1690,
 1512,
 1963,
 1825,
 1460,
 1828,
 1902,
 1874,
 1755,
 1951,
 1830,
 1767,
 1787,
 1373,
 1709,
 1514,
 1807,
 1791,
 1724,
 1859,
 1590,
 1976,
 1572,
 1947,
 1913,
 1995,
 1728,
 1624,
 1731,
 1706,
 1782,
 1994,
 1851,
 1843,
 1773,
 1982,
 1685,
 2001,
 1346,
 1200,
 1746,
 1520,
 972,
 1834,
 1909,
 2008,
 1733,
 1960,
 1280,
 1879,
 1203,
 1979,
 1133,
 1647,
 1282,
 1684,
 860,
 1444,
 1780,
 1989,
 1795,
 1819,
 1797,
 1842,
 1796,
 1457,
 1839,
 1853,
 1711,
 1883,
 1146,
 1734,
 1389]

In [2]:
#1a
for i in input:
    for j in input:
        if i+j==2020:
            print(i*j)

100419
100419

In [3]:
#1b 
for i in input:
    for j in input:
        for k in input:
            if (i+j+k) == 2020:
                print(i*j*k)

265253940
265253940
265253940
265253940
265253940
265253940

In [4]:
#2a
import pandas as pd
input2 = pd.read_csv("adventofcode2.txt", sep= " ", header=None)
totalsum = 0
for row in input2.values:
    rowsum = 0
    for letter in row[2]:
        if letter == row[1][0]:
            rowsum += 1
    tmp = row[0].split("-")
    if rowsum >= int(tmp[0]) and int(tmp[1])>=rowsum:
        totalsum += 1
print(totalsum)

422

In [5]:
#2b

totalsum = 0
for row in input2.values[:]:
    rowsum = 0
    tmp = row[0].split("-")
    if row[2][int(tmp[0])-1] == row[1][0]:
        rowsum += 1
    if row[2][int(tmp[1])-1] == row[1][0]:
        rowsum += 1
    
    #print(tmp)
    if rowsum == 1:
        totalsum += 1
print(totalsum)

451

In [88]:
#3a
input2 = pd.read_csv("3a.txt", header=None)

def function3b(right, down):
    
    
    totalTree = 0
    position = 0
    for row_index in range(down,len(input2[0]),down):

        position += right
        
        if position >= len(input2[0][row_index]):
            position -= len(input2[0][row_index])
        #print(row_index)
        if input2[0][row_index][position] == "#":
            totalTree += 1
    
    return totalTree    

print(function3b(3,1))

153

In [90]:
#3b
function3b(1,1)*function3b(3,1)\
*function3b(5,1)*function3b(7,1)*function3b(1,2)

2421944712